version: "3.9"
services:
  db2:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5435:5432"
    volumes:
      - db2-data:/var/lib/postgresql/data

volumes:
  db2-data:
